controllers/UserController.php
<?php
namespace app\controllers;

use Yii;

use app\models\User;
use yii\web\View;
use yii\web\Controller;
use yii\db\IntegrityException;
use yii\web\NotFoundHttpException;
use yii\filters\{VerbFilter, AccessControl};
use yii\helpers\Url;
use yii\web\UploadedFile;

class UserController extends Controller
{
    public $password;
    public $defaultAction = 'setting';
    private $arrayActions = ['index', 'quote', 'poem', 'author',
                             'create', 'update', 'delete',
                             'create-author','update-author','delete-author',
                             'setting'];

    public function behaviors()
    {
        return [
                   'access' =>
                   [
                       'class' => AccessControl::className(),
                       'only' =>  $this->arrayActions,
                       'rules' => [
                           [
                               'roles' => ['?'],
                               'allow' => true,
                               'actions' => ['login'],
                           ],
                           [
                               'roles' => ['user'],
                               'allow' => true,
                               'actions' => $this->arrayActions,
                           ],
                       ],
                   ],
                   'verbs' => [
                       'class' => VerbFilter::className(),
                       'actions' => [
                           'delete' => ['post'],
                           'delete-author' => ['post'],
                       ],
                   ],
               ];
    }


    public function actionIndex()
    {
            return $this->render('index');
    }

    public function actionSetting()
    {
        $model = User::findIdentity(Yii::$app->user->identity->id);

        if ($model->load(Yii::$app->request->post()) ) {

            $model->setPassword($model->password);

            if ($model->save()) {
                Yii::$app->session->setFlash('success', Yii::t('app', 'The data saved correctly'));
            } else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Unexpected problem'));
            }

            return $this->redirect(['setting']);
        } else {
            return $this->render('setting', ['model' => $model]);
        }

    }





}

views/layouts/_footer.php
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//stats.pceuropa.net/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '22']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

views/layouts/_navbar.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use pceuropa\languageSelection\LanguageSelection;
use yii\helpers\StringHelper;
use lajax\translatemanager\models\Language;


$languages = [
  'pl' => 'pl',
  'en' => 'en',
];
  
NavBar::begin([
    'brandLabel' => Html::img('@img/logo.png'),
    'brandUrl' => Url::to(['/forms/module/index']),
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
$blog = (yii::$app->language == 'pl') ? '/blog/pl/' : '/blog/';

$m = [
     '<li>'.Html::a ('<span class="glyphicon glyphicon-home" aria-hidden="true"></span>', ['/forms/module/index'] ).'</li>',
     ['label' => Yii::t('app', 'Forms'), 'url' => ['/forms/module/index']],
     ['label' => Yii::t('app', 'Contact'), 'url' => ['/site/contact']],
];

if (Yii::$app->user->isGuest) {
    $m[] = ['label' => Yii::t('app', 'Login'), 'url' => ['/site/login']];
    $m[] = ['label' => Yii::t('app', 'Signup'), 'url' => ['/site/signup']];
} else {
    $m[] = ['label' => Yii::t('app', 'Your profil'), 'items' => [
           ['label' => Yii::t('app', 'Your forms'), 'url' => ['/forms/module/user']],
           ['label' => Yii::t('app', 'Add form'), 'url' => ['/forms/module/create']],
           ['label' => Yii::t('app', 'Settings'), 'url' => ['/user/setting']],
           '<li>' . Html::beginForm(['/site/logout'], 'post') .
           Html::submitButton( 'Logout (' . Yii::$app->user->identity->username . ')', ['class' => 'btn btn-link logout']) . Html::endForm() . '</li>',
           ]];

}

if (\Yii::$app->user->can('admin' )) {
    $m[] =  ['label' => Yii::t('app', 'Tr'), 'items' => [
            ['label' => Yii::t('app', 'Languages'), 'url' => ['/translatemanager/language/list', 'LanguageSearch[status]' => 1]],
            ['label' => Yii::t('app', 'create'), 'url' => ['/translatemanager/language/create']],
            ['label' => Yii::t('app', 'scan'), 'url' => ['/translatemanager/language/scan']],
            ['label' => Yii::t('app', 'optimzer'), 'url' => ['/translatemanager/language/optimzer']],
            ['label' => Yii::t('language', 'Import'), 'url' => ['/translatemanager/language/import']],
            ['label' => Yii::t('language', 'Export'), 'url' => ['/translatemanager/language/export']],
            ]];
}

$m[] = LanguageSelection::widget([
              'language' => $languages,
              'languageParam' => 'lang'
          ]);

echo Nav::widget([ 'options' => ['class' => 'navbar-nav navbar-right'], 'items' => $m ]);

NavBar::end();

?>

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
use app\widgets\Alert;
AppAsset::register($this);

?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <meta property="og:url"           content="<?php echo Yii::$app->request->absoluteUrl; ?>" />
    <meta property="og:type"          content="website" />
    <meta property="og:image"         content="https://form.pceuropa.net/images/logo.png" />
</head>

<body>
<?php $this->beginBody() ?>

		<?= $this->render('_navbar');?>

		<div class="wrap container">
		    <?= Breadcrumbs::widget([ 
		    	'homeLink' => [
    				'label' => '<span class="glyphicon glyphicon-home" aria-hidden="true"></span>',
		  			'encode' => false,
		  			'url' => Url::home(),
					],
		    	'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [], ]) ?>
            <?= Alert::widget() ?>

		    <?= $content ?>
              <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- Your share button code -->
  <div class="pull-right fb-share-button"
    data-href="<?php echo Yii::$app->request->absoluteUrl; ?>"
    data-layout="button_count">
  </div>
		</div>
		
<?= $this->render('_footer.php'); ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>